"""add tables

Revision ID: 75915f1c563d
Revises: 
Create Date: 2018-07-30 22:17:10.090401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75915f1c563d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_trial_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_trial_id', sa.Integer(), nullable=True),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runner.id'], ),
    sa.ForeignKeyConstraint(['time_trial_id'], ['time_trial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_trial_result')
    op.drop_table('time_trial')
    op.drop_table('runner')
    # ### end Alembic commands ###
